import { brandConfig } from "./brandConfig";

export const siteConfig = {
  title: `${brandConfig.name} — Sabiduría de los Arcanos | Tarot, Astrología & Academia en Monterrey y México`,
  titleTemplate: `%s | ARCANO — Tarot y Astrología Monterrey & México`,
  description:
    "Tarot profesional, Carta Astral y Astrología en Monterrey y México. Academia mística, oráculo diario y lecturas privadas con El Señor de los Arcanos.",
  url: "https://arcanosolutions.com",
  ogImage: "https://arcanosolutions.com/og-arcano.jpg",
  author: "ARCANO Solutions",
  keywords: [
    // Prioridad Local: Monterrey & Zona Metropolitana
    "tarot monterrey",
    "lectura de tarot monterrey",
    "tarot san pedro garza garcia",
    "carta astral monterrey",
    "astrologia monterrey",
    "tarotistas en monterrey",
    "cursos de tarot monterrey",
    "academia de tarot monterrey",
    "tarot obispado monterrey",
    "tarot valle oriente",
    "reiki monterrey",
    "numerologia monterrey",
    "sinastria de parejas monterrey",
    "consultas de tarot nuevo leon",
    // Prioridad Nacional: Todo México
    "tarot mexico",
    "lectura de tarot online mexico",
    "tarotista profesional mexico",
    "carta astral mexico",
    "astrologia mexico",
    "tarot terapeutico mexico",
    "sinastria amorosa mexico",
    "cursos esotericos online mexico",
    "aprender tarot mexico",
    "academia de astrologia mexico",
    // Disciplinas y conceptos clave de búsqueda
    "arcanos mayores",
    "significado arcanos mayores",
    "arcanos menores",
    "carta del dia",
    "carta del tarot de hoy",
    "oraculo diario",
    "tarot del amor",
    "tarot evolutivo",
    "psicologia arquetipica",
    "simbolismo mistico",
    "sabiduria de los arcanos",
    "tarot profesional y proposito",
    "tienda esoterica mexico",
  ],
  locale: "es_MX",
};
